package com.nusaproperty.app.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryNavy = Color(0xFF0C3B5E)
val PrimaryDark = Color(0xFF002540)
val PrimaryContainer = Color(0xFF0C3B5E)
val OnPrimary = Color(0xFFFFFFFF)
val OnPrimaryContainer = Color(0xFF7FA6CE)
val PrimaryFixed = Color(0xFFCFE5FF)
val PrimaryFixedDim = Color(0xFFA4CAF4)
val OnPrimaryFixed = Color(0xFF001D34)
val OnPrimaryFixedVariant = Color(0xFF20496D)

val SecondaryAmber = Color(0xFFF4A261)
val SecondaryBrown = Color(0xFF8E4E14)
val SecondaryContainer = Color(0xFFFFAB69)
val OnSecondary = Color(0xFFFFFFFF)
val OnSecondaryContainer = Color(0xFF783D01)
val SecondaryFixed = Color(0xFFFFDCC4)
val SecondaryFixedDim = Color(0xFFFFB780)
val OnSecondaryFixed = Color(0xFF2F1400)
val OnSecondaryFixedVariant = Color(0xFF6F3800)
val AccentGold = Color(0xFFDDA15E)

val TertiaryTeal = Color(0xFF0F4C5C)
val TertiaryDark = Color(0xFF002731)
val TertiaryContainer = Color(0xFF003E4D)
val OnTertiary = Color(0xFFFFFFFF)
val OnTertiaryContainer = Color(0xFF75A9BC)
val TertiaryFixed = Color(0xFFB6EBFE)
val TertiaryFixedDim = Color(0xFF9ACEE1)
val OnTertiaryFixed = Color(0xFF001F28)
val OnTertiaryFixedVariant = Color(0xFF114D5D)

val StatusSuccess = Color(0xFF2A9D8F)
val StatusPending = Color(0xFFE9C46A)
val StatusInfo = Color(0xFF1976D2)
val StatusError = Color(0xFFBA1A1A)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)

val SurfaceCanvas = Color(0xFFF8F9FA)
val SurfaceCard = Color(0xFFFFFFFF)
val SurfaceLow = Color(0xFFF3F4F5)
val SurfaceContainerLow = Color(0xFFF3F4F5)
val SurfaceNormal = Color(0xFFEDEEEF)
val SurfaceContainer = Color(0xFFEDEEEF)
val SurfaceHigh = Color(0xFFE7E8E9)
val SurfaceContainerHigh = Color(0xFFE7E8E9)
val SurfaceHighest = Color(0xFFE1E3E4)
val SurfaceVariant = Color(0xFFE1E3E4)
val OnSurface = Color(0xFF191C1D)
val OnSurfaceVariant = Color(0xFF42474E)
val InverseSurface = Color(0xFF2E3132)
val InverseOnSurface = Color(0xFFF0F1F2)

val TextPrimary = Color(0xFF0A1D2B)
val TextSecondary = Color(0xFF5C6B73)
val BorderSubtle = Color(0xFFE5E9ED)
val OutlineColor = Color(0xFF72777F)
val OutlineVariant = Color(0xFFC2C7CF)